src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrer</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected position is no longer open to new applications.</errorMessage>
            <filterItems>
                <field>QSF_RFL_Position__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QSF_RFL_Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>App-{00000000}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Application_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>QSF_RFL_Application__c</referenceTo>
        <relationshipLabel>Application Attachments</relationshipLabel>
        <relationshipName>Application_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Curriculum Vitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Candidate_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>QSF_RFL_Application__c</referenceTo>
        <relationshipLabel>Candidate Skills</relationshipLabel>
        <relationshipName>Candidate_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <formula>Required_Skill__r.Skill__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Skill</label>
        <type>Text</type>
    </fields>
    <label>Candidate Skill</label>
    <nameField>
        <label>Skill Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Skills</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Position__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <description>The budget assigned for the open position</description>
        <label>Budget</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City office where the employee will be based</description>
        <label>City</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <defaultValue>Today() + 90</defaultValue>
        <description>Deadline for the hiring to be effective. Notifications will be sent to hiring managers one week before the deadline if the position is not fulfilled.</description>
        <label>Deadline</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Manager the headcount belongs to</description>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Managed_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Referral Fee</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the recruitment process</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>QSF_RFL_Application__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recommendation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The referrer not only wants to refer this person but also recommends him</description>
        <inlineHelpText>The referrer not only wants to refer this person but also recommends him</inlineHelpText>
        <label>Recommendation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Relative/Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Have worked with him</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred by someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Required_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>QSF_RFL_Position__c</referenceTo>
        <relationshipLabel>Required Skills</relationshipLabel>
        <relationshipName>Required_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>QSF_RFL_Skill__c</referenceTo>
        <relationshipLabel>Required Skills</relationshipLabel>
        <relationshipName>Required_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Required Skill</label>
    <nameField>
        <displayFormat>Skill-{0000000}</displayFormat>
        <label>Skill Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QSF_RFL_ReferralsAppTests.cls
@isTest(seeAllData=true)
private class QSF_RFL_ReferralsAppTests {
    public static User hiringManager;
    public static List<QSF_RFL_Skill__c> skills;
    public static List<QSF_RFL_Required_Skill__c> requiredSkills;
    public static List<QSF_RFL_Position__c> positions;
    public static List<QSF_RFL_Application__c> applications;
    public static Contact contact;
    
    static void init(boolean createReferral) {
        hiringManager = new User();
        hiringManager.Username= 'fake@company.com';
        hiringManager.Email = 'fake@company.com';
        hiringManager.Lastname = 'mike';
        hiringManager.Alias = 'fakem';
        hiringManager.TimeZoneSidKey = 'GMT';
        hiringManager.LocaleSidKey = 'en_US';
        hiringManager.EmailEncodingKey = 'ISO-8859-1';
        hiringManager.LanguageLocaleKey = 'en_US';
        hiringManager.ProfileId = UserInfo.getProfileId();
        insert(hiringManager);
        
        contact = new Contact(Email = 'test@test.com', LastName = 'Tester');
        insert(contact);
        
        skills = new List<QSF_RFL_Skill__c>();
        requiredSkills = new List<QSF_RFL_Required_Skill__c>();
        positions = new List<QSF_RFL_Position__c>();
        applications = new List<QSF_RFL_Application__c>();
        
        QSF_RFL_Skill__c s1 = new QSF_RFL_Skill__c();
        s1.Name = '5 years experience';
        skills.add(s1);
        
        QSF_RFL_Skill__c s2 = new QSF_RFL_Skill__c();
        s2.Name = 'References Provided';
        skills.add(s2);
        
        insert(skills);     
        
        QSF_RFL_Position__c p1 = new QSF_RFL_Position__c();
        p1.Name = 'Madrid -- Human Resources Manager';
        p1.Budget__c = 60000;
        p1.City__c = 'Madrid';
        p1.Deadline__c = Date.today().addDays(180);
        p1.Geography__c = 'EMEA';
        p1.Hiring_Manager__c = hiringManager.Id;
        p1.Referral_Fee__c = 2000;
        p1.Status__c = 'Open';
        positions.add(p1);
        
        QSF_RFL_Position__c p2 = new QSF_RFL_Position__c();
        p2.Name = 'Lisbon -- Coorporate Finance Assistant';
        p2.Budget__c = 40000;
        p2.City__c = 'Lisbon';
        p2.Deadline__c = Date.today().addDays(180);
        p2.Geography__c = 'EMEA';
        p2.Hiring_Manager__c = hiringManager.Id;
        p2.Referral_Fee__c = 1000;
        p2.Status__c = 'Closed - Selected';
        positions.add(p2);
        
        insert(positions);
        
        QSF_RFL_Required_Skill__c rs1 = new QSF_RFL_Required_Skill__c();
        rs1.Position__c = p1.Id;
        rs1.Skill__c = s1.Id;
        requiredSkills.add(rs1);
        
        QSF_RFL_Required_Skill__c rs2 = new QSF_RFL_Required_Skill__c();
        rs2.Position__c = p1.Id;
        rs2.Skill__c = s2.Id;
        requiredSkills.add(rs2);
        
        insert(requiredSkills);
        
        if (createReferral) {
            QSF_RFL_Application__c app = new QSF_RFL_Application__c();
            app.Position__c = positions[0].id;
            app.Contact__c = contact.id;
            app.Status__c = 'Waiting';
            insert app;
            applications.add(app);

            QSF_RFL_Referral__c ref = new QSF_RFL_Referral__c();
            ref.Application__c = app.Id;
            ref.Name = 'Referral Test';
            ref.Relationship__c = 'Have Worked With Him';
            ref.Recommendation__c = true;
            ref.Referrer__c = UserInfo.getUserId();
            insert ref;
        }
    }
    
    static testMethod void testApplicationSelectedTrigger() {
        init(true);
        Test.startTest();
        applications[0].status__c = 'Accepted';
        update(applications[0]);
        QSF_RFL_Position__c position = [Select Id, Status__c From QSF_RFL_Position__c Where Id = :applications[0].Position__c];
        System.assert(position.Status__c == 'Closed - Selected');
        Test.stopTest();
    }

    /** Test with skills trigger **/
    static testMethod void testNewApplicationTrigger() {
        init(false);
        Test.startTest();
     
        QSF_RFL_Application__c app1 = new QSF_RFL_Application__c();
        app1.Position__c = positions[0].id;
        app1.Contact__c = contact.id;
        app1.Status__c = 'Waiting';

        insert app1;
        
        //Test 1: Inserted
        System.assert(app1.Id != null);
        
        //Test 2: Check candidate skills created
        List<QSF_RFL_Candidate_Skill__c> cSkills = [SELECT Id, Skill__c 
                                                    FROM QSF_RFL_Candidate_Skill__c
                                                    WHERE Application__c = :app1.id];

        System.assert(requiredSkills.size() == cSkills.size());
        
        Test.stopTest();
    }

    /** Test new Referral Controller **/
    public static testMethod void testNewReferralController() {
        init(false);
        Test.startTest();
        PageReference pageRef = Page.QSF_RFL_NewReferralPage;
        Test.setCurrentPage(pageRef);
        
        List<String> cities = QSF_RFL_NewReferralController.getCitiesForPositionsInGeo('EMEA');
        System.assert(cities.size() > 0);
        
        List<Object> ps = QSF_RFL_NewReferralController.getPositionsInCity('All');
        System.assert(ps.size() > 0);
        
        QSF_RFL_Position__c position = QSF_RFL_NewReferralController.getPosition(positions[0].id);
        System.assert(position.Name != null);

        Map<String, String> values = new Map<String, String>();
        values.put('position', positions[0].id);
        values.put('name', 'Daniel');
        values.put('fName', 'Tester');
        values.put('email', 'test2@test.com');
        values.put('phone', '+34917000000');
        values.put('relation', 'Have Worked With Him');
        values.put('recommend', 'true');
        values.put('comments', 'Test comments');
        
        Map<String, String> res = QSF_RFL_NewReferralController.createReferral(values);
        System.assert(res.get('result') == 'OK');
        String refId = res.get('referralId');
        String appId = res.get('applicationId');

        ApexPages.currentPage().getParameters().put('idRef', refId);
        QSF_RFL_NewReferralController controller = new QSF_RFL_NewReferralController();
        controller.currentReferralId = refId;
        
        controller.appAttachment.Application__c = appId;
        controller.appAttachment.Type__c = 'Other';
        controller.Attachment.Name = 'Unit Test Attachment';
        controller.Attachment.Body = Blob.valueOf('Unit Test Attachment Body');
        controller.upload();

        List<QSF_RFL_Application_Attachment__c> atts = QSF_RFL_NewReferralController.getAttachments(appId);
        System.assert(atts.size() == 1);
        
        Test.stopTest();
    }
    
    /** Test with skills trigger **/
    static testMethod void testReferralListController() {
        init(true);
        Test.startTest();
        PageReference pageRef = Page.QSF_RFL_ReferralListPage;
        Test.setCurrentPage(pageRef);
        QSF_RFL_ReferralListController contrl = new QSF_RFL_ReferralListController();
        
        Test.stopTest();
    }
}