src/objects/Lunch_Meetup__c.object
<CustomObject>
    <label>Lunch Meetup</label>
    <nameField>
        <label>Lunch Meetup Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lunch Meetups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lunch_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Lunch Participants</relationshipLabel>
        <relationshipName>Lunch_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lunch_Meetup__c</fullName>
        <label>Lunch Meetup</label>
        <referenceTo>Lunch_Meetup__c</referenceTo>
        <relationshipLabel>Lunch Participants</relationshipLabel>
        <relationshipName>Lunch_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lunch Participant</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lunch Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunch Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WFL_AddParticipantInCalendar.cls
global with sharing class WFL_AddParticipantInCalendar {
    
    webservice static String addParticipant(String userId, String lunchMeetup) {
        try {System.debug('WFL - ' + userId + ' - ' + lunchMeetup);
             
             Event e = [select id, subject, StartDateTime, WhatId, OwnerId
                        from Event where WhatId =: lunchMeetup limit 1];
             
             //Verify if Participant already exists
             List<Lunch_Participant__c> lpT = [select id, name from Lunch_Participant__c
                                         where Employee__c =: userId AND Lunch_Meetup__c =: lunchMeetup];
             if (lpT != null && lpT.size() > 0)
             {
                 System.debug('WFL - Participant is already attending the lunch meetup');
                 return 'You are already attending this lunch meetup';
             }
             
             EventRelation er = new EventRelation(EventId = e.Id, 
                                                  RelationId = userId);
             Database.DMLOptions dlo = new Database.DMLOptions();
             dlo.EmailHeader.triggerUserEmail  = true;
             dlo.EmailHeader.triggerOtherEmail  = true;
             dlo.EmailHeader.triggerAutoResponseEmail = false;
             Database.insert(er,dlo);
             
             //Create Participant
             Lunch_Participant__c lp = new Lunch_Participant__c();
             lp.Employee__c = userId;
             lp.Lunch_Meetup__c = lunchMeetup;
             insert(lp);
             
             return '';
            }
        catch (Exception ex) {
            System.debug('WFL - Error while adding Participant to Calendar Event, m=' + ex.getMessage());
            return 'Error while adding Participant to Calendar Event, m=' + ex.getMessage();
        }
    }
}