src/objects/Lunch__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Lunch Date</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cooking the lunch menu</fullName>
                <color>#FF6600</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch menu ready</fullName>
                <color>#009900</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Special</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Lunch ID.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lunch_Meetup__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address of the lunch meetup</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lunch__c</fullName>
        <label>Lunch</label>
        <referenceTo>Lunch__c</referenceTo>
        <relationshipLabel>Lunch Meetups</relationshipLabel>
        <relationshipName>Lunch_Meetups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Brasserie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pic-nic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandwich</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch Meetup</label>
    <nameField>
        <label>Lunch Meetup Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lunch Meetups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WFL_NewLunchMeetup.cls
public class WFL_NewLunchMeetup {
    public List<SelectOption> typeOfLunchMeetup {get; set;}
    
    public WFL_NewLunchMeetup() {
        typeOfLunchMeetup = new List<SelectOption>();
        for(Schema.PicklistEntry e : Lunch_Meetup__c.Type__c.getDescribe().getPicklistValues()){
            typeOfLunchMeetup.add(new SelectOption(e.getValue(), e.getLabel()));
        }
    }
    
    @RemoteAction 
    public static List<String> getDates() {
        try {
            // Getting the next 3 lunch date available
            List<Lunch__c> lunchs = [select id, name, Date__c, Status__c
                                     from Lunch__c
                                     where Date__c >= TODAY AND Status__c = 'Lunch menu ready' ORDER BY Date__c ASC limit 5];
            
            List<String> dates = new List<String>();
            Date current = Date.today();
            for (Lunch__c lunch : lunchs) {
                dates.add(lunch.Date__c.format());
            }
            return dates;
        } catch (Exception e) {
            System.debug('WFL - Cannot get Dates, m=' + e.getMessage());
            return null;
        }
    }
    
    @RemoteAction 
    public static Map<String, String> createLunchMeetup(Map<String, String> values) {
        try {
            String lunchDate = values.get('lunchDate');
            String lunch_name = values.get('lunch_name');
            String location = values.get('location');
            String startTime = values.get('startTime');
            String endTime = values.get('endTime');
            String typeOfLunch = values.get('typeOfLunch');
            System.debug('WFL - New Lunch Meetup - Parsing Selected Date ' + lunchDate);
            
            Date lDate = Date.parse(lunchDate);
            integer shour = Integer.valueOf(startTime.substring(0, 2));
            integer sminute = Integer.valueOf(startTime.substring(3, 5));
            integer ssecond = Integer.valueOf(startTime.substring(6, 8));
            
            integer ehour = Integer.valueOf(endTime.substring(0, 2));
            integer eminute = Integer.valueOf(endTime.substring(3, 5));
            integer esecond = Integer.valueOf(endTime.substring(6, 8));
            
            DateTime lSDateTime = DateTime.newInstance(lDate.year(), lDate.month(), lDate.day(),
                                                      shour, sminute, ssecond);
            DateTime lEDateTime = DateTime.newInstance(lDate.year(), lDate.month(), lDate.day(),
                                                      ehour, eminute, esecond);
            
            if (lEDateTime.getTime() - lSDateTime.getTime() <= 0)
            {
                System.debug('WFL - Lunch duration should be greater than 0 minute');
                return new Map<String, String>{'type' => 'KO', 'result' => 'KO', 'message' => 'Lunch duration should be greater than 0 minute'};
            }
            
            System.debug('WFL - StartTime:' + startTime.substring(0, 2) + ' - ' + shour + ' - ' + sminute + ' - ' + ssecond);
            System.debug('WFL - EndTime:' + endTime.substring(3, 5) + ' - ' + ehour + ' - ' + eminute + ' - ' + esecond);
            
            List<Lunch__c> lunchs = [Select id, Name, Date__c from Lunch__c Where Date__c = :lDate LIMIT 10];
            if (lunchs == null || lunchs.size() == 0)
            {
                System.debug('WFL - No related lunch while creating Lunch Meetup for date: ' + lunchDate);
                return new Map<String, String>{'type' => 'KO', 'result' => 'KO', 'message' => 'There is no lunch available for that date'};
            }
            System.debug('WFL - Lunch for selected Lunch Meetup: ' + lunchs.get(0).Date__c);
            
            Lunch_Meetup__c lm = new Lunch_Meetup__c();
            lm.Name = lunch_name;
            lm.Lunch__c = lunchs.get(0).Id;
            lm.Address__c = location;
            lm.Start_Date_Time__c = lSDateTime;
            lm.End_Date_Time__c = lEDateTime;
            lm.Type__c = typeOfLunch;
            
            insert(lm);
            
            return new Map<String, String>{'type' => 'OK', 'result' => 'OK', 'message' => 'OK', 'lunchId' => lunchs.get(0).Id};
                } catch (Exception e) {
                	System.debug('WFL - Cannot create lunch meetup, m=' + e.getMessage());
                    return new Map<String, String>{'type' => 'exception', 'result' => 'KO', 'message' => e.getMessage()};
                }
    }
}