src/objects/Lunch__c.object
<CustomObject>
    <fields>
        <fullName>Appetizer__c</fullName>
        <description>Appetizer</description>
        <label>Appetizer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Lunch Date</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Desert__c</fullName>
        <label>Desert</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lunch_Meetups__c</fullName>
        <label>#Lunch Meetups</label>
        <summaryForeignKey>Lunch_Meetup__c.Lunch__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Special_Menu__c</fullName>
        <label>Special Menu</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cooking the lunch menu</fullName>
                <color>#FF6600</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch menu ready</fullName>
                <color>#009900</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Special</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Lunch ID.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunches</pluralLabel>
    <recordTypes>
        <fullName>Special</fullName>
        <active>true</active>
        <description>Special Lunch</description>
        <label>Special</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lunch_Meetup__c.object
<CustomObject>
    <fields>
        <fullName>Lunch__c</fullName>
        <label>Lunch</label>
        <referenceTo>Lunch__c</referenceTo>
        <relationshipLabel>Lunch Meetups</relationshipLabel>
        <relationshipName>Lunch_Meetups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Brasserie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pic-nic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandwich</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch Meetup</label>
    <nameField>
        <label>Lunch Meetup Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lunch Meetups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WFL_TodayController.cls
public class WFL_TodayController {
    
    public Lunch__c todaysLunch {get;set;}
    public String lunchDescription {get;set;}
    public List<String> lmOrganisers {get;set;}
    public String lunchPictureUrl {get;set;}
        
        public WFL_TodayController () {
            loadTodaysLunch();
        }
    
    private void loadTodaysLunch() {
        try {
            todaysLunch = [select id, name, Lunch_Meetups__c,
                           Appetizer__c, Course__c, Date__c,
                           Desert__c, Special_Menu__c, Status__c, Type__c, RecordTypeId
                           from Lunch__c WHERE Date__c = TODAY AND Status__c = 'Lunch menu ready' LIMIT 1 ];
            
            List<Attachment> pictureAttachments = [SELECT Id, Name, Body, ContentType FROM Attachment 
                 WHERE parentId = :todaysLunch.id ORDER BY CreatedDate DESC];
            
            if (pictureAttachments.size() > 0) {
                lunchPictureUrl = '/servlet/servlet.FileDownload?file=' + pictureAttachments[0].id;
            }
            
            List<Lunch_Meetup__c> lms = [select
                                     id, Name, Start_Date_Time__c, CreatedById, Lunch__c
                                     from Lunch_Meetup__c lm where Lunch__c = :todaysLunch.id
                                     ORDER BY Start_Date_Time__c DESC
                                     limit 10];

            lmOrganisers = new List<String>();
            for (Lunch_Meetup__c lm : lms) {
                System.debug('WFL - Querying Each Lunch Meetup for the Organizer, size=' + lms.size() + ' - lm=' + lm.Name);
                User u = [select id, Name, SmallPhotoUrl from User Where id =: lm.CreatedById limit 1];
                    lmOrganisers.add(u.SmallPhotoUrl);
            }
                
            if (todaysLunch == null)
                return;
            if (todaysLunch.Type__c == 'Special')
            {
                if (todaysLunch.Special_Menu__c != null)
                    lunchDescription = todaysLunch.Special_Menu__c;
            }
            else {
                lunchDescription = '';
                if (todaysLunch.Appetizer__c != null)
                    lunchDescription += '<b>Appetizer</b><br/>' + todaysLunch.Appetizer__c + '<br/>';
                if (todaysLunch.Course__c != null)
                    lunchDescription += '<b>Course</b><br/>' + todaysLunch.Course__c + '<br/>';
                if (todaysLunch.Desert__c != null)
                    lunchDescription += '<b>Dessert</b><br/>' + todaysLunch.Desert__c + '<br/>';
            }
            if (lunchDescription == '')
                lunchDescription = 'Details not yet available';
        } catch (Exception e) {
            System.debug('WFL - Cannot retrieve todays lunch, m=' + e.getMessage());
        }
    }
    
}