src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_Idea_Age__c</fullName>
        <formula>(ROUND(Now () - CreatedDate,0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Idea Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_Number_of_Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Comments and Posts attached to an idea via the feed.</description>
        <inlineHelpText>Number of Comments and Posts attached to an idea via the feed.</inlineHelpText>
        <label>Number of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Reviewed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Under Consideration by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mode</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse_Submitted_By__c</fullName>
        <formula>CreatedBy.FirstName  &amp; &quot; &quot;&amp; CreatedBy.LastName &amp; &quot; on &quot; &amp;  TEXT(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submitted By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pse_VotesDown__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Down</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_VotesUp__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pse_customeIdeasTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class pse_customeIdeasTest {


    public static ApexPages.StandardSetController setCon;
    public static pse_customIdeasController controller;
    public static pse_Idea__c idea;
    
    static void init() {
    	
    	if (controller == null) {
	    	setCon = new ApexPages.StandardSetController(Database.getQueryLocator( 
	                    [SELECT pse_Title__c, 
	        					pse_Number_of_Comments__c,pse_VotesUp__c,pse_VotesDown__c,pse_Status__c,
	        					pse_Submitted_By__c, pse_Idea_Age__c  
	        					FROM pse_Idea__c FOR REFERENCE]));
	        					
	        controller = new pse_customIdeasController(setCon);
    	}
    	
        idea = pse_testDataFactory.createTestIdea ();
        
        try {
        	insert idea;
        }
		catch (DmlException e) {
    		System.debug(e.getMessage());
		}
    }


	@IsTest
    public static void testCreateIdeaController() {
    	Test.startTest();
    	init(); 
    	controller.createIdea();
    	Test.stopTest();
    }
    
    @IsTest
    public static void testDomainController() {
   		Test.startTest();
    	init();    
       
        String baseURL = controller.getDomain(); 
        //System.assertEquals('https://eu5.salesforce.com',baseURL);
        System.assertEquals(System.Url.getSalesforceBaseURL().toExternalForm(),baseURL);
        Test.stopTest();
    }
    
    @IsTest public static void testInrementVoteController() {
    	Test.startTest();
    	init();
    	
        boolean isIncrementResult = pse_customIdeasController.voteHandler(idea.id,'increment');

        
        pse_Idea__c idea1 = [SELECT pse_VotesUp__c from pse_Idea__c where id = :idea.id LIMIT 1];
        
        System.assertEquals(idea1.pse_VotesUp__c,1);        
   		Test.stopTest();
    } 
    
    @IsTest public static void testIncrementVoteTwiceController() {
    	Test.startTest();
    	init();
    	
        boolean isIncrementResult = pse_customIdeasController.voteHandler(idea.id,'increment');

        pse_Idea__c idea1 = [SELECT pse_VotesUp__c from pse_Idea__c where id = :idea.id LIMIT 1];
        
        System.assertEquals(idea1.pse_VotesUp__c,1); 
        
        //Now ry to vote again for the same idea with a vote down, it should not work because we have already
        //voted with a vote up just before (can't voe twice.
        
        boolean isDecrementResult = pse_customIdeasController.voteHandler(idea.id,'increment');
        //Number of votesUp should still be equal to 1, not 2.
        System.assertEquals(idea1.pse_VotesUp__c,1);        
   		Test.stopTest();
    }
    
    @IsTest public static void testDecrementVoteController() {
    	Test.startTest();
    	init();
    	
        boolean isDecrementResult = pse_customIdeasController.voteHandler(idea.id,'decrement');

        pse_Idea__c idea1 = [SELECT pse_VotesDown__c from pse_Idea__c where id = :idea.id LIMIT 1];
        
        System.assertEquals(idea1.pse_VotesDown__c,-1);        
   		Test.stopTest();
    }    
           
}