src/objects/pse_Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_Approver_11__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Approver_22__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ideas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Approver_33__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ideas2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>pse_Category__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Pain_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pain point, if any, to be solved by this idea.</description>
        <inlineHelpText>Pain point, if any, to be solved by this idea.</inlineHelpText>
        <label>Pain Point</label>
        <referenceTo>pse_Pain_Point__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Reviewed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Under Consideration by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mode</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pse_VotesUp__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Idea_Rules_Evaluation__c.object
<CustomObject>
    <description>Rules to decide :
 - how many points are required to submit ideas to the innovation committee
 - who and how many approvers are required based on the innovation type (breakthrough, incremental, etc)</description>
    <fields>
        <fullName>pse_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of first approver.</description>
        <inlineHelpText>Name of first approver.</inlineHelpText>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Idea_Rules_Evaluation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of second approver.</description>
        <inlineHelpText>Name of second approver.</inlineHelpText>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Idea_Rules_Evaluation1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of third approver.</description>
        <inlineHelpText>Name of third approver.</inlineHelpText>
        <label>Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Idea_Rules_Evaluation2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Criteria__c</fullName>
        <formula>CASESAFEID(pse_Innovation_Category__c) + &quot;:&quot; + TEXT(pse_Points__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Criteria</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse_Innovation_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Category of Innovation as defined by the users on the Category Object.</description>
        <label>Category</label>
        <referenceTo>pse_Category__c</referenceTo>
        <relationshipLabel>Idea Rules Evaluation</relationshipLabel>
        <relationshipName>Idea_Rules_Evaluation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Pain_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paint point or challenge to be solved by the idea.</description>
        <inlineHelpText>Paint point or challenge to be solved by the idea.</inlineHelpText>
        <label>Pain Point</label>
        <referenceTo>pse_Pain_Point__c</referenceTo>
        <relationshipLabel>Idea Rules Evaluation</relationshipLabel>
        <relationshipName>Idea_Rules_Evaluation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Points__c</fullName>
        <description>Number of points required to submit ideas automatcally to the Innovation Committee.</description>
        <inlineHelpText>Number of points required to submit ideas automatcally to the Innovation Committee.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea Rule Evaluation</label>
    <nameField>
        <displayFormat>RULE-{0000}</displayFormat>
        <label>Idea Rules Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idea Rules Evaluation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Pain_Point__c.object
<CustomObject>
    <description>Contains pain points and challenges the company is facing.</description>
    <fields>
        <fullName>pse_Points__c</fullName>
        <description>Number of points earned if idea reached a certain number of votes.</description>
        <inlineHelpText>Number of points earned if idea reached a certain number of votes.</inlineHelpText>
        <label>Points To Be Earned</label>
        <picklist>
            <controllingField>pse_Incentive_Type__c</controllingField>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse_Status__c</fullName>
        <description>Status of the pain point or challenge.
Open : employees can post ideas to solve the challenges or pain points.
Close : employees can&apos;t post ideas to solve the challenges or pain points.</description>
        <inlineHelpText>Status of the pain point indicating whether or not employees can post ideas to solve challenges or pain points.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pain Point</label>
    <nameField>
        <label>Pain Point Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pain Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Projects__c.object
<CustomObject>
    <description>Projects are used to track ideas generated by the community, through to fruition. 

Each project is assigned a project team and this app is used to define the project, track it&apos;s stage, open issues, and estimated completion date.</description>
    <fields>
        <fullName>pse_Original_Idea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Idea</label>
        <referenceTo>pse_Idea__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>pse_pto_end_date__c</fullName>
        <description>End Date of vacation.</description>
        <inlineHelpText>End Date of vacation.</inlineHelpText>
        <label>PTO End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pse_pto_start_date__c</fullName>
        <description>Start Date of vacation.</description>
        <inlineHelpText>Start Date of vacation.</inlineHelpText>
        <label>PTO Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/pse_ideaTriggerHandler.cls
public with sharing class pse_ideaTriggerHandler {

    private static final String STAGE_NYR = 'Not Yet Reviewed';
    private static final String STAGE_UCC = 'Under Consideration by Committee';
    private static final String STAGE_BR = 'Rejected';
	private static final String STAGE_PM = 'Project Mode';
    private String currentStep;
	private String c;
	private pse_Category__c cat;
	
	public void routeApprovals(Map<Id, pse_Idea__c> oldIdeas, Map<Id, pse_Idea__c> newIdeas) {
        
		List<pse_Idea__c> ideas_to_route = new List <pse_Idea__c>();
		Set<String> criteria = new Set <String>();
	
		for(Id ideaId : oldIdeas.keySet()) {
			pse_Idea__c old_idea = oldIdeas.get(ideaId);
			pse_Idea__c new_idea = newIdeas.get(ideaId);
			
	
			//For now criteria to move to 'Under Consideration by Committee' status and assign aprrovers is
			//only based on the number of votes up.
			//In the next version, criticality, Innovation category, pain points will also be taken into account
	           
	        
	        if((new_idea.pse_Status__c == STAGE_NYR && old_idea.pse_Status__c == STAGE_NYR) 
	           && (old_idea.pse_VotesUp__c != new_idea.pse_VotesUp__c)) {
	    
				ideas_to_route.add(new_idea);
				criteria.add(new_idea.pse_Category__c + ':' + new_idea.pse_VotesUp__c);
				
					
	            //Reset the record's status and set approvers to null 
				new_idea.pse_Approver_11__c = null;
	            new_idea.pse_Approver_22__c = null;
	            new_idea.pse_Approver_33__c = null;
			} 
			//If status transitions from "Under Consideration by Committee" to "Project Mode", create
			//a new record in the Projects Object.
			else if (old_idea.pse_Status__c == STAGE_UCC && new_idea.pse_Status__c == STAGE_PM ) {

				pse_Projects__c project = new pse_Projects__c (Name = new_idea.pse_Title__c);
				project.pse_Original_Idea__c = new_idea.id;
				 
				
				try {
					insert project;	
				}
				catch (DmlException e) {
    				System.debug(e.getMessage());
    				System.debug(e.getStackTraceString());
				}
				
			}
	        else {
	            //do nothing if status is in anything but 'Under Consideration by Committee' 
	            //'Under Consideration by Committee' => no need to select approvers, this has already been done
	            //'Rejected' nothing to be done as the idea has been rejected
	            //'Project Mode' nothing to be done as the idea has already been approved
	        }
	
		}

		
		if(!ideas_to_route.isEmpty()) {
			// fetch the matching routes


			List<pse_Idea_Rules_Evaluation__c> routes = [SELECT pse_Pain_Point__c, 
															pse_Criteria__c, 
															pse_Points__c, 
															pse_Approver_1__c,
															pse_Approver_2__c,
															pse_Approver_3__c, 
															pse_Innovation_Category__c 															
														FROM pse_Idea_Rules_Evaluation__c 
														]; 

																														
			Map<String, pse_Idea_Rules_Evaluation__c> routesByCriteria = new Map<String, pse_Idea_Rules_Evaluation__c>();
	
			for(pse_Idea_Rules_Evaluation__c route : routes) {
				routesByCriteria.put(route.pse_Criteria__c, route); 
			}
	
	        //Update Approvers only if the number of votes for a given Innovation Category has reached the threshold set
	        //in the "Idea Rules Evaluation" 
			for(pse_Idea__c idea : ideas_to_route) {
				pse_Idea_Rules_Evaluation__c route = routesByCriteria.get(idea.pse_Category__c + ':' + idea.pse_VotesUp__c);				
	
				//we have a hit !
				if(null != route) {
					idea.pse_Approver_11__c = getApprover(route.pse_Approver_1__c);
					idea.pse_Approver_22__c = getApprover((null == route.pse_Approver_2__c) ? idea.pse_Approver_11__c : route.pse_Approver_2__c);
					idea.pse_Approver_33__c = getApprover((null == route.pse_Approver_3__c) ? idea.pse_Approver_22__c : route.pse_Approver_3__c);
					
					
					//Now update the status
					idea.pse_Status__c = STAGE_UCC;
								
					
				}
	
	            // Cannot leave any approver related-user field empty
				else {
					// prevent mistaken routes by resetting approvers if route cannot be found.
					idea.pse_Approver_11__c = null; 
	                idea.pse_Approver_22__c = null;
	                idea.pse_Approver_33__c = null;
				}
	
			}//end of for	
		}//end of if
		
	}
	
    
    public String getApprover(String primaryApproverId) {
    	String approverId = primaryApproverId;
        Date startDate;
        Date endDate;
        String delegatedApproverId;
        
        try {
        	User user = [SELECT DelegatedApproverId, pse_pto_start_date__c, pse_pto_end_date__c FROM USER WHERE Id = :primaryApproverId LIMIT 1];
            
            if(user.DelegatedApproverId != null && user.pse_pto_start_date__c != null && user.pse_pto_end_date__c != null) {
                
                startDate = Date.valueOf(user.pse_pto_start_date__c);
                endDate = Date.valueOf(user.pse_pto_end_date__c);
                delegatedApproverId = String.valueOf(user.DelegatedApproverId);
                
                if(startDate <= Date.today() || endDate >= Date.today()) {
                    approverId = delegatedApproverId;

                }    
        	}
        }
        
        catch(DmlException e) {
    		System.debug(e.getMessage());
    		System.debug(e.getStackTraceString());
		}
    
        return approverId;
    }
    
}