src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_VotesDown__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Down</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_VotesUp__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Vote__c.object
<CustomObject>
    <description>Contains information about votes on ideas. Used to make :
 -  sure a user only votes once
 - reports &amp; dashboards</description>
    <fields>
        <fullName>Idea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the idea record an employee has voted on.</description>
        <inlineHelpText>Id of the idea record an employee has voted on.</inlineHelpText>
        <label>Idea</label>
        <referenceTo>pse_Idea__c</referenceTo>
        <relationshipLabel>Votes</relationshipLabel>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Has_Voted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the employee has voted.</description>
        <inlineHelpText>Indicates whether or not the employee has voted.</inlineHelpText>
        <label>Has Voted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse_VoteDown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The employee doesn&apos;t like this idea.</description>
        <inlineHelpText>The employee doesn&apos;t like this idea.</inlineHelpText>
        <label>VoteDown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse_VoteUp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The employee likes this idea.</description>
        <inlineHelpText>The employee likes this idea.</inlineHelpText>
        <label>VoteUp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse_Voter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the employee that has voted.</description>
        <inlineHelpText>Id of the employee that has voted.</inlineHelpText>
        <label>Voter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <label>Vote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pse_customIdeasController.cls
global class pse_customIdeasController {
    public pse_Idea__c idea;
    public String id;
    Integer vote;
    public static pse_Idea__c myIdea;
    public static pse_Vote__c v;
    public static boolean voteResult  { get; set; }    
    public String ideaId { get; set; }
    
    
    public pse_customIdeasController (ApexPages.StandardSetController stdController) {
        this.idea = (pse_Idea__c)stdController.getRecord();

    }
    
    
    public PageReference createIdea(){
        
       Schema.DescribeSObjectResult r;
       
       try{

           r = pse_Idea__c.SObjectType.getDescribe();

           
       }
       catch(Exception e){
         ApexPages.addMessages(e);
       }
       
       //Go to standard creation page for pse_Idea__c and rturn to VF page 
       //if cancel button is hit on the Stanard pse_Idea__c page
       return new PageReference('/' + r.getKeyPrefix() + '/e?retURL=/apex/pse_customIdeas');
      
    }
    
       

    @RemoteAction
     global static boolean voteHandler(String id, String flag) {
        voteResult = false;
        
        myIdea = [SELECT pse_VotesUp__c, pse_VotesDown__c  FROM pse_Idea__c
                   WHERE Id = :id];
  

        try {        
          //Check if user has already voted
          List <pse_Vote__c> votes = [SELECT id  FROM pse_Vote__c WHERE Idea__c = :id 
                                      AND pse_Voter__c = :UserInfo.getUserId()];
        

          if(votes.size() == 0 ) {
          	//the user did not vote yet, so let's allow him to vote and create a vote reord to make sure he won't be able 
          	//to vote on the same idea again
            //System.debug('customIdeas : RemoteAction : in incrementVote() : in ! (votes.size() > 0 : myIdea.pse_VotesUp__c = ' + myIdea.pse_VotesUp__c);
            
            v = new pse_Vote__c (pse_Has_Voted__c = true);
            v.pse_Voter__c = UserInfo.getUserId();
            v.Idea__c = id;
            
            if(flag == 'increment') {
              myIdea.pse_VotesUp__c += 1;
              v.pse_VoteUp__c = true;		
            }
            else {
              myIdea.pse_VotesDown__c -= 1;
              v.pse_VoteDown__c = true;            	
            }
            
            update myIdea;
            insert v;

            voteResult = true;
            
          }
          
        }
        catch(System.DMLException e) {
            ApexPages.addMessages(e);
        }
        
        return voteResult;
    }
    
    
    public String getDomain() {
        return System.Url.getSalesforceBaseURL().toExternalForm();
    } 
    
}