src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_Number_of_Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Comments and Posts attached to an idea via the feed.</description>
        <inlineHelpText>Number of Comments and Posts attached to an idea via the feed.</inlineHelpText>
        <label>Number of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pse_postCommentTriggerTest.cls
@isTest
private class pse_postCommentTriggerTest {
	
	public static pse_Idea__c idea;
	public static FeedItem myFeed;
	
	static void init() {
		idea = pse_testDataFactory.createTestIdea ();
		insert idea;
		
		myfeed = pse_testDataFactory.createTestFeed (idea.id); 
		insert myFeed;
	}
	
	@IsTest public static void testAddCommentTrigger() {
		
		Test.startTest();
		init();
								        
	
		pse_Idea__c idea1 = [SELECT pse_Number_of_Comments__c from pse_Idea__c where id = :idea.id LIMIT 1];
		
		//Now check that the number of comments has been incremented
		System.assertEquals(idea1.pse_Number_of_Comments__c,1);
		
		Test.stopTest();
	}
	
	@IsTest public static void testDeleteCommentTrigger() {
		
		Test.startTest();
		init();
		
		//delete post
		myfeed = [SELECT id from FeedItem where id = :myFeed.id LIMIT 1];
		
		try {
			delete myfeed;
		}
		catch (DmlException e) {
    		System.debug('An unexpected error has occurred: ' + e.getMessage());
		}
		
		pse_Idea__c idea1 = [SELECT pse_Number_of_Comments__c from pse_Idea__c where id = :idea.id LIMIT 1];
		
		//Now check that the number of comments has been decremented to 0
		System.assertEquals(idea1.pse_Number_of_Comments__c,0);
		
		Test.stopTest();
	}

}