src/objects/PSE_Employee_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>PSE_Believe_budget__c</fullName>
        <description>How strongly do you believe in an on-budget completion of the project on a scale from 1 to 5 (1=strongly believe, 5=do not believe)</description>
        <label>Believe in on-budget project completion</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Believe_success__c</fullName>
        <description>How strongly do you believe in the success of the project on a scale from 1 to 5 (1=strongly believe, 5=do not believe)</description>
        <label>Believe in success of project</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Believe_time__c</fullName>
        <description>How strongly do you believe in an on-time completion of the project on a scale from 1 to 5 (1=strongly believe, 5=do not believe)</description>
        <label>Believe in on-time project completion</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Current_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Project</label>
        <referenceTo>PSE_PulseCheck_Project__c</referenceTo>
        <relationshipLabel>Employee Feedbacks</relationshipLabel>
        <relationshipName>Employee_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSE_Feel_expectations_realistic__c</fullName>
        <description>Do you feel that the expectations put to you by management are realistic (1=very realistic, 5=unrealistic)</description>
        <label>Feel that expectations are realistic</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Feel_positively_challenged__c</fullName>
        <description>Do you feel positively challenged with your work (1=fully agree, 5=do not agree)</description>
        <label>Feel positively challenged</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Feel_pressure__c</fullName>
        <description>Do you feel under pressure with your work (1=high pressure, 5=low pressure)</description>
        <label>Feel under pressure</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Required_to_work_more_productively__c</fullName>
        <description>What areas should we improve upon to allow you to work more productively</description>
        <label>Required to work more productively</label>
        <picklist>
            <picklistValues>
                <fullName>Technical equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workspace environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager&apos;s communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team&apos;s communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work load management</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>PSE_Send_copy_to_line_manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send copy to line manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSE_Send_copy_to_project_manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send copy to project manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSE_What_could_we_have_done_better__c</fullName>
        <label>What could we have done better</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PSE_What_should_we_change__c</fullName>
        <label>What should we change</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PSE_What_went_well_this_week__c</fullName>
        <label>What went well this week</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Employee Feedback</label>
    <nameField>
        <displayFormat>F-{000000000}</displayFormat>
        <label>Employee Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Feedbacks</pluralLabel>
    <recordTypes>
        <fullName>PSE_Employee_Feedback_Project</fullName>
        <active>true</active>
        <description>Give feedback on specific project you have been working on this week</description>
        <label>Employee Feedback Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>PSE_Employee_Feedback_Work</fullName>
        <active>true</active>
        <description>Give feedback on your general work environment and conditions this week</description>
        <label>Employee Feedback Work</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSE_PulseCheck_Project__c.object
<CustomObject>
    <fields>
        <fullName>PSE_End_Date__c</fullName>
        <defaultValue>TODAY()+90</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSE_Is_Executive_sponsored__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Executive sponsored?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSE_Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Managed_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSE_Project_Priority__c</fullName>
        <label>Project Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSE_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSE_Setup_Pulse_Check.cls
public class PSE_Setup_Pulse_Check {
    public static PageReference listView(Schema.sObjectType destinationSObject) {
        Schema.DescribeSObjectResult destination = destinationSObject.getDescribe();
        PageReference pageRef = new PageReference('/' + destination.getKeyPrefix() );
        pageRef.setRedirect(true);
        return pageRef;
    }

    /*
    public static PageReference landingPage(Schema.sObjectType destinationSObject) {
        Schema.DescribeSObjectResult destination = destinationSObject.getDescribe();
        PageReference pageRef = new PageReference('/' + destination.getKeyPrefix() + '/o' );
        pageRef.setRedirect(true);
        return pageRef;
    }
    */

    public static Integer rand(Integer max) {
        return (Integer) (Math.random() * max);
    }
    public static Boolean randBoolean() {
        return (Math.random() > 0.5 ? true : false);
    }
    
    public Integer numOfProjects { get; set; }
    public Integer numOfFeedbacks { get; set; }

    private String[] projectNames;
    private String[] priorities;
    private String[] reqEff;

    public PSE_Setup_Pulse_Check() {
        numOfFeedbacks = 50;
        
        String projectNamesString = 'Project Cloud,Project X,Archimedes,Migration to Salesforce,SAP Upgrade,Upgrade to Oracle 12,Project Chrome,Apollo Program,Encryption Deployment,Quick Start Apps';
        projectNames = projectNamesString.split(',');
        numOfProjects = projectNames.size();
        
        priorities = 'High,Medium,Low'.split(',');
        reqEff = 'Technical equipment,Workspace environment,Team work,Manager\'s communication,Team\'s communication,Work load management)'.split(',');
    }

    public PageReference createSampleData() {
        System.debug('createSampleData() called.');

        RecordType rtProject = [
            SELECT Id,Name,DeveloperName 
            FROM RecordType 
            WHERE DeveloperName='PSE_Employee_Feedback_Project' 
            LIMIT 1][0];
        RecordType rtWork = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName='PSE_Employee_Feedback_Work' 
            LIMIT 1][0];

        System.debug('rtProject: ' + rtProject.Id);
        System.debug('rtWork: ' + rtWork.Id);

        PSE_PulseCheck_Project__c[] projects = new List<PSE_PulseCheck_Project__c>();
        User[] users = [SELECT Id, Name FROM User WHERE UserType='Standard' LIMIT 20];

        for(Integer i=0; i<numOfProjects; i++) {
            Integer userIndex = rand(users.size()); 
            User projectManager = users[userIndex];
            Integer priorityIndex = rand(priorities.size());
            String priority = priorities[priorityIndex];

            PSE_PulseCheck_Project__c p = new PSE_PulseCheck_Project__c(
                Name = projectNames[i],
                PSE_Is_Executive_sponsored__c = randBoolean(),
                PSE_Project_Manager__c = projectManager.Id,
                PSE_Project_Priority__c = priority,
                PSE_Start_Date__c = Date.today().addDays(-rand(100)),
                PSE_End_Date__c = Date.today().addDays(rand(100))
            );    
            projects.add(p);
        }
        insert projects;

        PSE_Employee_Feedback__c[] feedbacks = new List<PSE_Employee_Feedback__c>();

        for(Integer i=0; i<numOfFeedbacks; i++) {
            Integer userIndex = (Integer) (Math.random() * users.size()); 
            User employee = users[userIndex];
            
            PSE_Employee_Feedback__c feedback;
            if(Math.mod(i,2) == 0) {
                feedback = new PSE_Employee_Feedback__c(
                    RecordTypeId = rtProject.Id,
                    OwnerId = employee.Id,
                    PSE_Believe_budget__c = String.valueOf(rand(5)+1),
                    PSE_Believe_success__c = String.valueOf(rand(5)+1),
                    PSE_Believe_time__c = String.valueOf(rand(5)+1),
                    PSE_Current_Project__c = projects[Math.mod(i, projects.size())].Id,
                    PSE_Send_copy_to_line_manager__c = false,
                    PSE_Send_copy_to_project_manager__c = false,
                    PSE_What_could_we_have_done_better__c = 'Text',
                    PSE_What_should_we_change__c = 'Text',
                    PSE_What_went_well_this_week__c = 'Text'
                );
            }
            else {
                feedback = new PSE_Employee_Feedback__c(
                    RecordTypeId = rtWork.Id,
                    OwnerId = employee.Id,
                    PSE_Feel_expectations_realistic__c = String.valueOf(rand(5)+1),
                    PSE_Feel_positively_challenged__c = String.valueOf(rand(5)+1),
                    PSE_Feel_pressure__c = String.valueOf(rand(5)+1),
                    //PSE_Required_to_work_more_productively__c = 'multipicklist (Technical equipment, Workspace environment, Team work, Manager\'s communication, Team\'s communication, Work load management)',
                    PSE_Send_copy_to_line_manager__c = false,
                    PSE_Send_copy_to_project_manager__c = false,
                    PSE_What_could_we_have_done_better__c = 'Text',
                    PSE_What_should_we_change__c = 'Everything',
                    PSE_What_went_well_this_week__c = 'Nothing'
                );
            }
            feedbacks.add(feedback);
        }
        insert feedbacks;

        return listView(PSE_Employee_Feedback__c.sObjectType);
    }

    public PageReference deleteData() {
        for(PSE_Employee_Feedback__c[] feedbacks: [SELECT Id FROM PSE_Employee_Feedback__c]) {
            delete feedbacks;
        }
        for(PSE_PulseCheck_Project__c[] projects: [SELECT Id FROM PSE_PulseCheck_Project__c]) {
            delete projects;    
        }
        return listView(PSE_Employee_Feedback__c.sObjectType);
    }

}