src/objects/pse_Category__c.object
<CustomObject>
    <fields>
        <fullName>pse_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>pse_Category__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Number_of_Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Comments and Posts attached to an idea via the feed.</description>
        <inlineHelpText>Number of Comments and Posts attached to an idea via the feed.</inlineHelpText>
        <label>Number of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Reviewed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Under Consideration by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mode</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pse_VotesDown__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Down</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse_VotesUp__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Votes Up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Idea_Rules_Evaluation__c.object
<CustomObject>
    <description>Rules to decide :
 - how many points are required to submit ideas to the innovation committee
 - who and how many approvers are required based on the innovation type (breakthrough, incremental, etc)</description>
    <fields>
        <fullName>pse_Innovation_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Category of Innovation as defined by the users on the Category Object.</description>
        <label>Category</label>
        <referenceTo>pse_Category__c</referenceTo>
        <relationshipLabel>Idea Rules Evaluation</relationshipLabel>
        <relationshipName>Idea_Rules_Evaluation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Points__c</fullName>
        <description>Number of points required to submit ideas automatcally to the Innovation Committee.</description>
        <inlineHelpText>Number of points required to submit ideas automatcally to the Innovation Committee.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Idea Rule Evaluation</label>
    <nameField>
        <displayFormat>RULE-{0000}</displayFormat>
        <label>Idea Rules Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idea Rules Evaluation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pse_testDataFactory.cls
public with sharing class pse_testDataFactory {
	
	public static pse_Idea__c createTestIdea () {
		String title = String.valueof(System.Math.random());
		pse_Idea__c idea = new pse_Idea__c (pse_Title__c = title, 
        									pse_VotesUp__c =0,
        									pse_VotesDown__c =0,
        									pse_Number_of_Comments__c = 0,
        									pse_Status__c = 'Not Yet Reviewed');

        																		
        return idea;
	}
	
	public static FeedItem createTestFeed (String id) {

		FeedItem myFeed = new FeedItem(parentId = id,
									 Body ='test post'
									 );    									
        									
        return myFeed;
	}
	
	public static pse_Category__c createTestCategory () {

		pse_Category__c cat = new pse_Category__c (Name = 'Innovation Category Test', 
														  	pse_Description__c = 'Description test');
		  									
        									
        return cat;
	}	


	public static User createTestUser (String id) {

		User user;
		try {
			Profile p = [SELECT Id from Profile where Name = 'Standard User'];
		

		
			user = new User (Lastname = 'testLastName' + id,
	                         FirstName = 'testFirstName' + id,
	                         Title = 'QA',
	                         Department = 'Test Department',
	                         Email = 'test@gmail.com',
	                         Phone = '+33123456789',
	                         MobilePhone = '+33123456789',
	                         TimeZoneSidKey = 'Europe/Paris',
	                         LocaleSidKey = UserInfo.getLocale(),
	                         EmailEncodingKey = 'ISO-8859-1', 
	                         LanguageLocaleKey = 'fr',
	                         Username ='ra_test' + id + '@test.com',
	                         Alias= 'test' + id,
	                         CommunityNickname ='test' + id, 
	                         ProfileId = p.id
	                      );
		}
		catch (DmlException e) {
    		System.debug(e.getMessage());
		}   									
        									
        return user;
	}
	
	public static pse_Idea_Rules_Evaluation__c createTestRule (String id) {

		
		pse_Idea_Rules_Evaluation__c rule = new pse_Idea_Rules_Evaluation__c (pse_Points__c = 1, 
														  	pse_Innovation_Category__c = id); 
 
														  										        									
        return rule;
	}

}