src/objects/pse_Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Idea__c.object
<CustomObject>
    <fields>
        <fullName>pse_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>pse_Category__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Reviewed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Under Consideration by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Mode</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse_Under_Consideration__c.object
<CustomObject>
    <fields>
        <fullName>pse_Status__c</fullName>
        <formula>IF(ISPICKVAL( pse_idea__r.pse_Status__c , &quot;Under Consideration by Committee&quot;), TEXT(pse_idea__r.pse_Status__c), NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse_idea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the idea being reviewed. Used to update the fields of the Under Review Object with formulas.</description>
        <label>Idea</label>
        <referenceTo>pse_Idea__c</referenceTo>
        <relationshipLabel>Under Consideration</relationshipLabel>
        <relationshipName>Under_Consideration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse_under_review_since__c</fullName>
        <description>Date at which the idea is under review by the innovation committe.</description>
        <inlineHelpText>Date at which the idea is under review by the innovation committe.</inlineHelpText>
        <label>under review since</label>
        <type>Date</type>
    </fields>
    <label>Under Consideration</label>
    <nameField>
        <displayFormat>UC-{0000}</displayFormat>
        <label>Under Consideration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Under Consideration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pse_ideaTriggerHandlerAfterAfter.cls
public with sharing class pse_ideaTriggerHandlerAfterAfter {
 
    private static final String STAGE_NYR = 'Not Yet Reviewed';
    private static final String STAGE_UCC = 'Under Consideration by Committee';
    private static final String STAGE_BR = 'Rejected';
	private static final String STAGE_PM = 'Project Mode';
    private static String STEP1 = 'Committee Review';
    private String currentStep;
	private String c;
	private pse_Category__c cat;
	public static boolean isExecuting = false;
	
	public void routeApprovals(Map<Id, pse_Idea__c> oldIdeas, Map<Id, pse_Idea__c> newIdeas) {
        
        if(pse_ideaTriggerHandlerAfterAfter.isExecuting) {
        	//If trigger is already executing, leave in order to avoid recursion.
        	return;
        }
        isExecuting = true;
       
	
		for(Id ideaId : oldIdeas.keySet()) {
			pse_Idea__c old_idea = oldIdeas.get(ideaId);
			pse_Idea__c new_idea = newIdeas.get(ideaId);


	        if(new_idea.pse_Status__c == STAGE_UCC && old_idea.pse_Status__c == STAGE_NYR ) {
	        
	    		submitIdea(new_idea);
	    		
	    		//Create a record on the "Under Consideration" Object
				pse_Under_Consideration__c underConsideration = new pse_Under_Consideration__c(pse_under_review_since__c = Date.today());
				underConsideration.pse_idea__c = new_idea.id;
				
				
				try {
					insert underConsideration; 
				}
       			catch(DmlException e) {
   					System.debug(e.getStackTraceString());
				}

			} 

	        else {

	            //Do nothing
	        }
	
		}
		
	}
	
	public void submitIdea(pse_Idea__c a) {

		
		pse_Idea__c idea2 = new pse_Idea__c(Id = a.Id);
		idea2.pse_Status__c = STAGE_UCC;
		
		try {
			update idea2;
		}
		catch(DmlException e) {
   			System.debug(e.getStackTraceString());
		}

		
        // Create an approval request for the idea
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(idea2.Id);
        
        // Submit on behalf of a specific submitter 
        req1.setSubmitterId(idea2.OwnerId);
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('pse_Idea_Approval');
        req1.setSkipEntryCriteria(true);
        
        // Submit the approval request for the idea
        Approval.ProcessResult result = Approval.process(req1);
        
        // Verify the result
        System.assert(result.isSuccess());
		
	}
    


}