src/objects/QSF_RFL_Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected position is no longer open to new applications.</errorMessage>
            <filterItems>
                <field>QSF_RFL_Position__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QSF_RFL_Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>App-{00000000}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QSF_RFL_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>QSF_RFL_Application__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QSF_RFL_ReferralListController.cls
public class QSF_RFL_ReferralListController {
    public List<Referral> referrals {get; set;}

    public class Referral {
        public String sfid {get; set;}
        public String name {get; set;}
        public String contactName  {get; set;}
        public String applicationStatus {get; set;}
        public String positionName {get; set;}
        public String positionHiringManager {get; set;}
        public String positionStatus {get; set;}
        public String positionReferralFee {get; set;}
        public String positionDeadline {get; set;}

        public Referral(QSF_RFL_Referral__c r) {
            sfid = r.Id;
            name = r.Name;
            contactName = r.Application__r.Contact__r.Name;
            applicationStatus = r.Application__r.Status__c;
            positionName = r.Application__r.Position__r.Name;
            positionHiringManager = r.Application__r.Position__r.Hiring_Manager__r.Name;
            positionStatus = r.Application__r.Position__r.Status__c;
            positionReferralFee = r.Application__r.Position__r.Referral_Fee__c + ' ' + UserInfo.getDefaultCurrency();
            
            Date dt = r.Application__r.Position__r.Deadline__c;
            positionDeadline = dt != null ? Datetime.newInstance(dt.year(), dt.month(), dt.day()).format('d MMMM yyyy') : 'Not Set';
        }

    }

    public QSF_RFL_ReferralListController() {
        String query = 'Select Id, Name, ' + 
                              'Application__r.Contact__r.Name, ' + 
                              'Application__r.Status__c, ' +  //Waiting, Process Started, Accepted, Rejected
                              'Application__r.Position__r.Name, ' + 
                              'Application__r.Position__r.Hiring_Manager__r.Name, ' + 
                              'Application__r.Position__r.Status__c, ' + //Not Started, Started, Candidate Selected, Completed, Cancelled
                              'Application__r.Position__r.Deadline__c ';
        
        if (UserInfo.isMultiCurrencyOrganization()) {
            query += ', convertCurrency(Application__r.Position__r.Referral_Fee__c) ';
        } else {
            query += ', Application__r.Position__r.Referral_Fee__c ';
        }

        query += ' FROM QSF_RFL_Referral__c ';
        query += ' WHERE Referrer__c = \'' + UserInfo.getUserId() + '\'';

        List<QSF_RFL_Referral__c> sfdcReferrals  = Database.query(query);

        referrals = new List<Referral>();
        for (QSF_RFL_Referral__c r : sfdcReferrals) {
            referrals.add(new Referral(r));
        }
    }
}